name: Windows 11 RDP with Ngrok

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip
        Expand-Archive ngrok-stable-windows-amd64.zip

    - name: Set up Ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        .\ngrok authtoken $NGROK_AUTH_TOKEN
        .\ngrok tcp 3389 &

    - name: Get Ngrok URL
      id: ngrok_url
      run: |
        echo "::set-output name=url::$(.\ngrok http 3389 --log=stdout | Select-String -Pattern 'tcp://.*?:(\d+)' -AllMatches | ForEach-Object { $_.Matches.Groups[1].Value })"

    - name: Print Ngrok URL
      run: |
        echo "RDP URL: ${{ steps.ngrok_url.outputs.url }}"
