name: SSH Remote RDP
run-name: SSH Remote RDP
env:
  # The name of the main module repository
  main_project_module: workspace
  
on:
  schedule:
    - cron: '0 */2 * * *'  # Schedule the workflow to run every 2 hours
  workflow_dispatch:  # Add workflow dispatch event for manual triggering
        
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Start SSH via tmate
      uses: rdp-studio/ssh2actions@main
      with:
        duration: '24h'  # Extend the duration to 24 hours
        keep_alive: 'true'  # Enable keep-alive
        keep_alive_message: 'Keeping the SSH session alive. Have a great day!'  # Custom keep-alive message
        # Add any other necessary configurations here
